# Generated by Django 4.2.6 on 2023-10-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megazzz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['-time_create'], name='megazzz_sho_time_cr_ec4b2a_idx'),
        ),
    ]
