# Generated by Django 4.2.6 on 2023-10-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megazzz', '0002_alter_shop_options_shop_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
